//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowProcess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowActivityStream
    {
        public int WorkflowActivityStreamID { get; set; }
        public Nullable<int> WorkflowID { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<int> Predecessor { get; set; }
        public Nullable<int> Successor { get; set; }
        public Nullable<int> JumpTo { get; set; }
        public string UserName { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual WorkFlow WorkFlow { get; set; }
    }
}
